services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true
        bind:
            #$bagName: '%resource_booking_bundle.session.attribute_bag_name%'

    _instanceof:
        Symfony\Bundle\FrameworkBundle\Controller\AbstractController:
            calls:
                - [ setContainer, [ '@service_container' ] ]

    Markocupic\GalleryCreatorBundle\:
        resource: ../../
        exclude: ../../{DependencyInjection,Resources,Model}

    Markocupic\GalleryCreatorBundle\Controller\ContentElement\GalleryCreatorController:
        tags:
            - { name: container.service_subscriber }
        public: true
        calls:
            - [ setContainer, [ '@Psr\Container\ContainerInterface' ] ]

    Markocupic\GalleryCreatorBundle\Controller\ContentElement\GalleryCreatorNewsController:
        tags:
            - { name: contao.content_element, category: gallery_creator_elements, template: ce_gallery_creator_news, type: gallery_creator_news }
            - { name: container.service_subscriber }
        public: true