services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true
        bind:
            $projectDir: '%kernel.project_dir%'
            $galleryCreatorUploadPath: '%markocupic_gallery_creator.upload_path%'
            $galleryCreatorBackendWriteProtection: '%markocupic_gallery_creator.backend_write_protection%'
            $galleryCreatorCopyImagesOnImport: '%markocupic_gallery_creator.copy_images_on_import%'
            $galleryCreatorReadExifMetaData: '%markocupic_gallery_creator.read_exif_meta_data%'

    _instanceof:
        Symfony\Bundle\FrameworkBundle\Controller\AbstractController:
            calls:
                - [ setContainer, [ '@service_container' ] ]

    Markocupic\GalleryCreatorBundle\:
        resource: ../../
        exclude: ../../{DependencyInjection,Resources,Model}

    Markocupic\GalleryCreatorBundle\Controller\ContentElement\GalleryCreatorController:
        tags:
            - { name: container.service_subscriber }
        public: true
        calls:
            - [ setContainer, [ '@Psr\Container\ContainerInterface' ] ]

    Markocupic\GalleryCreatorBundle\Controller\ContentElement\GalleryCreatorNewsController:
        tags:
            - { name: contao.content_element, category: gallery_creator_elements, template: ce_gallery_creator_news, type: gallery_creator_news }
            - { name: container.service_subscriber }
        public: true
